services:
  - type: web
    name: resume-ai-system
    env: python
    buildCommand: python build.py
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true --server.runOnSave=false --logger.level=info