services:
  - type: web
    name: resume-ai-system
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt && python -m nltk.downloader punkt stopwords
    startCommand: python -m streamlit run app.py --server.port=$PORT --server.headless=true --server.runOnSave=false
